apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: checkip
  labels:
    app: checkip
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: checkip
        tier: service
    spec:
      containers:
      - name: checkip
        image: "checkip:1"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5